name: Project Update
description: Update an existing project's information
title: "Update Project"
labels: ["update"]
body:
  - type: markdown
    attributes:
      value: |
        ## Update project information
        Use this form to fix broken URLs, update descriptions, or modify other project details.

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Project Selection"

  - type: dropdown
    id: project_id
    attributes:
      label: Project
      description: Select the project to update.
      options:
        - archimedes
        - bdsim
        - brian2
        - emerge
        - heavi
        - mesa
        - pathsim
        - pymunk
        - pysd
        - scikit-rf
        - thermal-engineering-systems-in-python-tespy
    validations:
      required: true

  - type: input
    id: reason
    attributes:
      label: Reason for Update
      description: Briefly explain why this update is needed.
      placeholder: "Fix broken documentation URL"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: |
        ### Updated Information
        Only fill in the fields you want to change. Leave others blank.

  - type: input
    id: tagline
    attributes:
      label: Tagline
      placeholder: "Leave blank to keep current"

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Leave blank to keep current"

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Updated Tags"

  - type: checkboxes
    id: tags
    attributes:
      label: Select new tags
      description: Only check if you want to replace the current tags. Leave all unchecked to keep current tags.
      options:
        - label: block-diagram
        - label: circuit
        - label: computational neuroscience
        - label: control
        - label: cycle simulation
        - label: digital-twin
        - label: dynamic-systems
        - label: electromagnetic
        - label: engineering
        - label: finite-element
        - label: heating
        - label: microwave
        - label: network
        - label: neuroscience
        - label: physics
        - label: powerplant
        - label: radio-frequency
        - label: refrigeration
        - label: rf
        - label: robotics
        - label: snn
        - label: spiking neural network
        - label: system-modeling
        - label: thermodynamics
        - label: transient
        - label: translation
        - label: vensim
        - label: visualization
        - label: xmile

  - type: input
    id: custom_tags
    attributes:
      label: Additional Tags
      description: Suggest new tags if needed, comma-separated.
      placeholder: "physics, thermal"

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Updated Links"

  - type: input
    id: docs
    attributes:
      label: Documentation
      placeholder: "Leave blank to keep current"

  - type: input
    id: pypi
    attributes:
      label: PyPI
      placeholder: "Leave blank to keep current"

  - type: input
    id: conda_forge
    attributes:
      label: Conda-Forge
      placeholder: "Leave blank to keep current"

  - type: input
    id: homepage
    attributes:
      label: Homepage
      placeholder: "Leave blank to keep current"

  - type: input
    id: example
    attributes:
      label: Example or Tutorial
      placeholder: "Leave blank to keep current"

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Updated Logo"

  - type: textarea
    id: logo
    attributes:
      label: Logo
      description: Drag and drop a new image, or paste a URL. Leave blank to keep current.
