name: Project Submission
description: Submit a Python simulation library to PySimHub
title: "New Project Submission"
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit your project to PySimHub
        Fill in the details below. A maintainer will review and add it to the catalog.

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Basic Information"

  - type: input
    id: name
    attributes:
      label: Project Name
      placeholder: "PathSim"
    validations:
      required: true

  - type: input
    id: tagline
    attributes:
      label: Tagline
      description: A short one-line description of your project.
      placeholder: "A dynamical system simulation framework in the block diagram paradigm"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A longer description. Markdown is supported.
      placeholder: "PathSim is a Python-native framework for modeling and simulating dynamical systems..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Tags"

  - type: checkboxes
    id: tags
    attributes:
      label: Select all tags that apply
      description: Pick at least one. You can suggest new tags in the additional tags field below.
      options:
        - label: block-diagram
        - label: calibration
        - label: circuit
        - label: computational neuroscience
        - label: control
        - label: cycle simulation
        - label: digital-twin
        - label: dynamic-systems
        - label: electromagnetic
        - label: emulation
        - label: engineering
        - label: finite-element
        - label: heating
        - label: microwave
        - label: network
        - label: neuroscience
        - label: physics
        - label: powerplant
        - label: radio-frequency
        - label: refrigeration
        - label: rf
        - label: robotics
        - label: sensitivity analysis
        - label: snn
        - label: spiking neural network
        - label: system-modeling
        - label: thermodynamics
        - label: transient
        - label: translation
        - label: uncertainty quantification
        - label: vensim
        - label: visualization
        - label: xmile

  - type: input
    id: custom_tags
    attributes:
      label: Additional Tags
      description: Suggest new tags if needed, comma-separated.
      placeholder: "physics, thermal"

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Links"

  - type: input
    id: github
    attributes:
      label: GitHub Repository
      placeholder: "https://github.com/pathsim/pathsim"
    validations:
      required: true

  - type: input
    id: docs
    attributes:
      label: Documentation
      placeholder: "https://docs.pathsim.org"

  - type: input
    id: pypi
    attributes:
      label: PyPI
      placeholder: "https://pypi.org/project/pathsim/"

  - type: input
    id: conda_forge
    attributes:
      label: Conda-Forge
      placeholder: "https://anaconda.org/conda-forge/pathsim"

  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: If different from docs or GitHub.
      placeholder: "https://pathsim.org"

  - type: input
    id: example
    attributes:
      label: Example or Tutorial
      placeholder: "https://docs.pathsim.org/examples/getting-started"

  - type: markdown
    attributes:
      value: "---"

  - type: markdown
    attributes:
      value: "### Logo"

  - type: textarea
    id: logo
    attributes:
      label: Logo
      description: Drag and drop a square image (PNG/SVG), or paste a URL. Falls back to GitHub avatar.
