name: Project Submission
description: Submit a Python simulation library to PySimHub
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        Fill in the JSON below with your project details. We'll review and add it to PySimHub.

  - type: textarea
    id: project_json
    attributes:
      label: Project Data
      description: Edit the JSON template below with your project info
      render: json
      value: |
        {
          "name": "",
          "tagline": "",
          "description": "",
          "tags": [],
          "github": "",
          "docs": "",
          "pypi": "",
          "condaForge": "",
          "homepage": "",
          "example": ""
        }
    validations:
      required: true

  - type: textarea
    id: logo
    attributes:
      label: Logo (optional)
      description: Drag and drop a square logo image here. We'll use your GitHub avatar as fallback.
